/*
 * Copyright (c) 2014, Fashiontec (http://fashiontec.org)
 * Licensed under LGPL, Version 3
 */

/*
 * Measurement model for the bodyapps backend. 
 * 
 * Model is defined via Mongoose. Measurement records can be uniquely identified 
 * by the measurement id (i.e. m_id).
 */
var uuid = require('node-uuid');
var mongoose = require('mongoose');

module.exports = mongoose.model('Measurement', {
  m_id: { type: String, default: function() { return uuid(); } }  
//measurement id(m_id) is generated by UUID on creation of a measurement record.
  ,m_unit: String
  ,m_timestamp: { type: Date, default: Date.now() }
  ,mid_neck_girth : Number
  ,bust_girth : Number
  ,waist_girth : Number
  ,hip_girth : Number
  ,across_back_shoulder_width : Number
  ,shoulder_drop : Number
  ,shoulder_slope_degrees :Number
  ,arm_length : Number
  ,wrist_girth : Number
  ,upper_arm_girth : Number
  ,armscye_girth : Number
  ,height : Number
  ,hip_height :Number
  ,person : {
    name: String
    ,email: String
    ,gender: String
    ,dob: { type: Date}
  }
  ,user_id : {type: String} //Schema.Types.ObjectId
});
