/*
 * Copyright (c) 2014 Fashiontec (http://fashiontec.org)
 * Licensed under LGPL Version 3
 */

/*
 * Measurement model for the bodyapps backend. 
 * 
 * Model is defined via Mongoose. Measurement records can be uniquely identified 
 * by the measurement id (i.e. m_id).
 */
var uuid = require('node-uuid');
var mongoose = require('mongoose');

module.exports = mongoose.model('Measurement', {
  m_id: { type: String, default: function() { return uuid(); } },
//measurement id(m_id) is generated by UUID on creation of a measurement record.
  m_unit: String,
  m_timestamp: { type: Date, default: Date.now }, // used for syncing with app.
  m_created: { type: Date, default: Date.now }, // used for HDF record
  height : Number,
  head_girth: Number,
  head_and_neck_length: Number,
  mid_neck_girth: Number,
  neck_base_girth: Number,
  shoulder_girth: Number,
  upper_chest_girth: Number,
  bust_girth: Number,
  under_bust_girth: Number,
  waist_girth: Number,
  waist_to_hip_height: Number,
  waist_to_knee_height: Number,
  waist_height: Number,
  side_waist_length: Number,
  center_front_waist_length: Number,
  center_back_waist_length: Number,
  shoulder_length: Number,
  shoulder_and_arm_length: Number,
  upper_front_chest_width: Number,
  front_chest_width: Number,
  across_front_shoulder_width: Number,
  across_back_shoulder_width: Number,
  upper_back_width: Number,
  back_width: Number,
  shoulder_width: Number,
  bustpoint_to_bustpoint: Number,
  halter_bustpoint_to_bustpoint: Number,
  neck_to_bustpoint: Number,
  shoulder_drop: Number,
  shoulder_slope_degree: Number,
  trunk_girth: Number,
  armscye_girth: Number,
  elbow_girth: Number,
  upper_arm_girth: Number,
  wrist_girth: Number,
  underarm_length: Number,
  cervical_to_wrist_length: Number,
  shoulder_to_elbow_length: Number,
  arm_length: Number,
  scye_depth: Number,
  hand_girth: Number,
  hand_length: Number,
  hand_width: Number,
  thumb_length: Number,
  index_finger_length: Number,
  middle_finger_length: Number,
  ring_finger_length: Number,
  little_finger_length: Number,
  thumb_width: Number,
  index_finger_width: Number,
  middle_finger_width: Number,
  ring_finger_width: Number,
  little_finger_width: Number,
  little_finger_length: Number,
  thumb_girth: Number,
  index_finger_girth: Number,
  middle_finger_girth: Number,
  ring_finger_girth: Number,
  little_finger_girth: Number,
  high_hip_girth: Number,
  hip_girth: Number,
  high_hip_height: Number,
  hip_height: Number,
  crotch_length: Number,
  crotch_height: Number,
  rise_height: Number,
  thigh_girth: Number,
  mid_thigh_girth: Number,
  knee_girth: Number,
  calf_girth: Number,
  ankle_girth: Number,
  cervical_to_knee_height: Number,
  cervical_height: Number,
  knee_height: Number,
  ankle_height: Number,
  foot_length: Number,
  foot_width: Number,
  foot_across_top: Number,
  arm_type: Number,
  back_shape: Number,
  chest_type: Number,
  shoulder_type: Number,
  stomach_shape: Number,
  images: [{
    rel: String,
    idref: String
  }
  ],
  person: {
    name: String,
    email: String,
    gender: String,
    dob: { type: Date},
    eye_color: String,
    hair_color: String,
    skin_complexion: String,
    blood_type: String,
    allergy: String,
    eye_performance: String,
  },
  deleted: { type: Boolean, default: false },
  user_id: {type: String} //Schema.Types.ObjectId
});
